"""Schemas for the /api/chat endpoint."""

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from app.models.user_schema import UserProfile


class ChatRole(str, Enum):
    user = "user"
    assistant = "assistant"


class ChatMessage(BaseModel):
    role: ChatRole
    content: str = Field(..., min_length=1, max_length=4000)


class ChatRequest(BaseModel):
    """
    Request body for POST /api/chat.

    `workout_plan` and `meal_plan` are the plain-text/markdown plans
    previously generated by /api/generate-plan for this user (the frontend
    is expected to hold on to them and pass them back so the assistant
    answers with full context). `history` is the recent conversation
    turns (frontend should trim to a reasonable window, e.g. last 10).
    """

    user: UserProfile
    workout_plan: Optional[str] = Field(default=None, max_length=6000)
    meal_plan: Optional[str] = Field(default=None, max_length=3000)
    message: str = Field(..., min_length=1, max_length=1000)
    history: List[ChatMessage] = Field(default_factory=list, max_length=20)
